config/routes.rb
# == Route Map
#
#                         Prefix Verb  URI Pattern                                   Controller#Action
#                    sidekiq_web       /sidekiq                                      Sidekiq::Web
#             download_recording GET   /recordings/:id/download(.:format)            recordings#download
#             checkout_recording GET   /recordings/:id/checkout(.:format)            recordings#checkout
#                                PATCH /recordings/:id/checkout(.:format)            recordings#process_checkout
#           start_over_recording PATCH /recordings/:id/start_over(.:format)          recordings#start_over
#         choose_video_recording PATCH /recordings/:id/choose_video(.:format)        recordings#choose_video
#                     recordings GET   /recordings(.:format)                         recordings#index
#                                POST  /recordings(.:format)                         recordings#create
#                  new_recording GET   /recordings/new(.:format)                     recordings#new
#                 edit_recording GET   /recordings/:id/edit(.:format)                recordings#edit
#                      recording GET   /recordings/:id(.:format)                     recordings#show
#                                PATCH /recordings/:id(.:format)                     recordings#update
#                                PUT   /recordings/:id(.:format)                     recordings#update
#                  callback_auth GET   /auth/callback(.:format)                      auths#callback
#                    logout_auth GET   /auth/logout(.:format)                        auths#logout
#                       new_auth GET   /auth/new(.:format)                           auths#new
# all_your_base_are_belong_to_us GET   /all_your_base_are_belong_to_us(.:format)     all_your_base_are_belong_to_us#index
#  all_your_base_are_belong_to_u GET   /all_your_base_are_belong_to_us/:id(.:format) all_your_base_are_belong_to_us#show
#                timezone_camera GET   /cameras/:id/timezone(.:format)               cameras#timezone
#     detect_timezone_api_camera GET   /api/cameras/:id/detect_timezone(.:format)    api/cameras#detect_timezone
#                           root GET   /                                             pages#index
#

Rails.application.routes.draw do

  # Sidekiq web UI
  # TODO přesunoutasi na samostatnou appku, nebo do raketasku
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  resources :recordings do
    member do
      get  :download
      get  :checkout
      post :checkout, action: :process_checkout
      patch :choose_video
    end
  end

  resource :auth, only: [:new, :callback] do
    get :callback, on: :member
    get :logout, on: :member
  end

  resources :all_your_base_are_belong_to_us, only: [:index, :show]

  resources :cameras, only: [] do
    get :timezone, on: :member
  end

  namespace :api do
    resources :cameras, only: [] do
      member do
        get :detect_timezone
      end
    end
  end

  root to: "pages#index"
end

app/models/recording.rb
# == Schema Information
#
# Table name: recordings
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  attempts             :integer          default(0), not null
#  video_settings_id    :integer
#  created_at           :datetime
#  updated_at           :datetime
#  final_video_id       :integer
#  user_id              :integer          not null
#  deleted_at           :datetime
#  preview_file_name    :string(255)
#  preview_content_type :string(255)
#  preview_file_size    :integer
#  preview_updated_at   :datetime
#

# Jedna koupena sluzba timelapse, s nazvem a informaci o zaplaceni
class Recording < ActiveRecord::Base

  attr_accessor :checkout_error

  # TODO extrahovat rozlišení obrázku https://github.com/thoughtbot/paperclip/wiki/Extracting-image-dimensions
  has_attached_file :preview, styles:         {thumb: "300x150>"},
                              preserve_files: true,
                              url:            "/system/:attachment/:id_partition/:hash.:extension",
                              hash_secret:    "my_little_secret_which_you_dont_know"#, # TODO přesunout do configu
                              # default_url:    "/images/:style/missing.png" # TODO něco jiného :)

  validates_attachment_content_type :preview, :content_type => //i # TODO validace stazeneho obrazku moc nefunguje

  before_save :extract_video_dimensions_from_preview

  acts_as_paranoid

  has_many :schedules, inverse_of: :recording, dependent: :destroy

  has_one :current_schedule, -> () { where(canceled_at: nil).order(created_at: :desc) },
          class_name: :Schedule,
          inverse_of: :recording

  accepts_nested_attributes_for :current_schedule
  validates :current_schedule, associated: true

  belongs_to :final_video, class_name: "Video"
  belongs_to :video_settings
  belongs_to :user

  before_validation :assign_camera_name
  before_create :assign_video_settings!

  delegate :start_at, :stop_at, to: :current_schedule
  delegate :api, to: :user

  def cancel!
    current_schedule.destroy
  end

  def set_final_video! id
    if video = current_schedule.videos.find(id)
      update_attribute(:final_video, video)
    end
  end

  def start!
    # Pokud selže vytváření Jobu, nestrhneme klientovi pokus
    Recording.transaction do
      increase_attempts!
      Daemons::Planner::create_snapshotters!(current_schedule)
    end
  end

  # Kód stavu v kterém se nahrávka nachází
  # before_start
  # recording
  # generating
  # choosing
  # done
  def state
    if current_schedule.error?
      :error
    elsif final_video_id?
      :done
    elsif current_schedule.video_generated?
      :choosing
    elsif Time.now.utc < current_schedule.make_utc_time(current_schedule.start_at)
      :before_start
    elsif Time.now.utc < current_schedule.make_utc_time(current_schedule.stop_at)
      :recording
    else
      :generating
    end
  end

  # TODO jen pro debug účely než bude vymyšlené placení ze strany C2S
  def paid?
    true
  end

  def pay
    start!
  rescue => ex
    self.checkout_error = ex
    false
  end

  def pay!
    start!
  end

  def update_video_dimensions!
    save(validate: false) if extract_video_dimensions_from_preview
  end

  private

  def assign_camera_name
    self.name = current_schedule.camera.shortname if current_schedule.camera_id_changed?
  end

  def increase_attempts!
    increment! :attempts
  end

  def assign_video_settings!
    self.video_settings = VideoSettings.current
  end

  def extract_video_dimensions_from_preview
    return unless preview?

    if pending_preview = preview.queued_for_write[:original]
      path = pending_preview.path
    else
      path = preview.staged_path || preview.path
    end

    return if path.nil?

    geometry = Paperclip::Geometry.from_file(path)

    self.video_height = geometry.height.to_i
    self.video_width  = geometry.width.to_i

    true
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController

  before_filter :load_recording, except: [:index, :new, :create]

  def index
    @recordings = current_user.recordings.order(created_at: :desc).preload(current_schedule: :filter)
  end

  def show
    render case @recording.state
           when :done
             :show
           when :choosing
             :choosing
           else
             :in_progress
           end
  end

  def new
    @recording = Recording.new
  end

  def create
    @recording = current_user.recordings.build(recording_params)

    respond_to do |format|
      # if @recording.save
      #   format.html { redirect_to checkout_recording_url(@recording) }
      if @recording.save and @recording.pay
        format.html { redirect_to recordings_url() }
      else
        format.html { render :new }
      end
    end
  end

  def checkout

  end

  def process_checkout
    if @recording.pay
      redirect_to recordings_url
    else
      flash.now[:error] = "Error during checkouting. Reason #{@recording.checkout_error.class.to_s}, #{@recording.checkout_error.message}"
      render :checkout
    end
  end

  def edit
    render :new
  end

  def update
    if @recording.update_attributes(recording_params)
      if @recording.paid?
        @recording.start!
        redirect_to recording_url(@recording)
      else
        redirect_to checkout_recording_url(@recording)
      end
    else
      render :new
    end
  end

  def destroy
    if @recording.destroy
      redirect_to new_recording_url
    else
      redirect_to recording_url(@recording)
    end
  end

  # def start_over
  #   if @recording.cancel!
  #     redirect_to edit_recording_url(@recording)
  #   else
  #     flash[:error] = "Can't start over ..."
  #     redirect_to recording_url(@recording)
  #   end
  # end

  def choose_video
    if @recording.set_final_video!(params[:video_id])
      redirect_to recording_url(@recording)
    else
      render :show
    end
  end

  def download
    @video = @recording.final_video

    send_file @video.video.path, type: @video.video_content_type
  end

  private

  def recording_params
    params.
      require(:recording).
      permit! # TMP chci povolit všechny parametry
      # permit(schedules_attributes: [
      #   :timezone, :camera_id,
      #   start_at_hash: [:date, :hour, :minute, :ampm], stop_at_hash: [:date, :hour, :minute, :ampm],
      #   filters_attributes: [from_hash: [:hour, :minute, :ampm], to_hash: [:hour, :minute, :ampm]]
      # ])
  end

  def load_recording
    @recording = current_user.recordings.find(params[:id])
  end
end

app/helpers/recordings_helper.rb
module RecordingsHelper

  def recording_image_icon_class recording
    case recording.state
      when :before_start
        klass = "preparing"
        icon  = "pause"
      when :recording
        klass = "recording"
        icon  = "stop"
      when :generating
        klass = "generating"
        icon  = "cogs"
      when :error
        klass = "error"
        icon  = "exclamation-triangle"
      else
        klass = "done"
        icon  = "play"
      end

    fa_icon icon, class: "recording__image-icon recording__image-icon--#{klass}"
  end

  # Popis stavu v kterém se nahrávka nachází
  def recording_state_text recording
    state    = recording.state
    schedule = recording.current_schedule

    content_tag :div, class: "recording__state recording__state--#{recording.state}" do
      case state
      when :before_start
        I18n.t("recording.states.#{state}.html", time: distance_of_time_in_words_to_now(schedule.make_utc_time(recording.start_at))).html_safe
      when :recording, :generating
        I18n.t("recording.states.#{state}.html", time: distance_of_time_in_words_to_now(schedule.make_utc_time(recording.stop_at))).html_safe
      else
        I18n.t("recording.states.#{state}.html", error: schedule.error_message).html_safe
      end
    end
  end

  def time_input param_prefix, value, params, defaults = {}
    params ||= {}

    concat(text_field_tag("#{param_prefix}[hour]",
                          value && value.strftime("%l") || params[:hour] || defaults[0],
                          class: "form-control input-hour",
                          maxlength: 2))

    concat(" : ")

    concat(text_field_tag("#{param_prefix}[minute]",
                          value && value.strftime("%M") || params[:minute] || defaults[1],
                          class: "form-control input-minute",
                          maxlength: 2))

    concat(" ")

    select_tag "#{param_prefix}[ampm]",
               options_for_select(%w(AM PM), value && value.strftime("%p") || params[:ampm] || defaults[2]),
               class: "select-ampm form-control"
  end

  def field_has_error_class obj, prop, class_name = "has-error"
    has_error(obj, prop) ? class_name : nil
  end

  def errors_for obj, prop
    if has_error(obj, prop)
      content_tag :label, class: "control-label recording-form__error-label" do
        safe_join get_errors(obj, prop), "<br>".html_safe
      end
    end
  end

  def has_error obj, prop
    obj.errors.has_key?(prop.to_sym)
  end

  def get_errors obj, prop
    obj.errors[prop.to_sym]
  end
end

app/views/recordings/_date_picker.html.erb
<div class="input-group recording-form__picker-input">
  <%= text_field_tag "#{schedule_form.object_name}[#{date_method}_hash][date]",
                     schedule_form.object.send(date_method) && schedule_form.object.send(date_method).strftime("%A %m/%d/%Y"),
                     class: "form-control pickadate",
                     placeholder: "Date" %>
  <span class="input-group-btn">
    <button class="btn <%= has_error(schedule_form.object, date_method) ? "btn-danger" : "btn-default" %>"
            data-trigger-pickadate="recording_current_schedule_attributes_<%= date_method %>_hash_date"
            type="button">
      <%= fa_icon "calendar" %>
    </button>
  </span>
</div>

app/views/recordings/_destroy_recording.html.erb
<%= form_for recording, method: :delete, html: {"data-confirm" => I18n.t('detail.destroy_comfirm')} do %>
  <button type="submit" class="btn btn-large btn-danger">
    <%= fa_icon "stop", text: t('in_progress.try_again.button') %>
  </button>
<% end %>

app/views/recordings/_recording.html.erb
<div class="col-md-10 col-md-offset-1 recording text-left">
  <% if recording.current_schedule %>
    <%= link_to recording_path(recording) do %>
      <div class="recording__description">
        <h3 class="recording__name">
          <%= recording.name %>
          <%= schedule_duration_in_words recording.current_schedule %>
        </h3>

<!-- Dočasně pro debug účely zobrazit celé časové nastavení videa -->
        <%= render_cell :recording, :setup, recording: recording %>

<!--
        <div class="recording__date recording__date--light">
          <%= recording.current_schedule.start_at.strftime("%b. %d, %Y") %> -
          <%= recording.current_schedule.stop_at.strftime("%b. %d, %Y") %>
        </div>
 -->

        <%= recording_state_text recording %>
      </div>

      <div class="recording__image"
           <% if recording.preview.present? %>style="background-image:url('<%= recording.preview.url(:thumb) %>');"<% end %>
           >
        <div class="recording__image-round"></div>
        <%= recording_image_icon_class recording %>
      </div>
    <% end %>
  <% else %>
    TODO - You have X more attempts to create time-lapse you will love.
    <%= link_to "Create new one", edit_recording_path(recording) %>
  <% end %>

  <div class="clearfix"></div>
</div>

app/views/recordings/checkout.html.erb
<div class="col-md-8 col-md-offset-2 text-center">
  <h1><%= t 'checkout.title' %></h1>

  <%= alerts %>

  <hr class="v-space large">

  <%= render @recording %>

  <hr class="v-space large">

  <div class="pull-right">
    <%= form_for @recording, url: checkout_recording_path(@recording) do |form|%>
      <button type="submit" class="btn btn-lg btn-success">
        <%= fa_icon "arrow-right", text: t('checkout.continue'), right: true %>
      </button>
    <% end %>
  </div>

  <div class="pull-left recording-checkout__back">
    <%= link_to edit_recording_path(@recording) do %>
      <%= fa_icon "arrow-left", text: t('checkout.back') %>
    <% end %>
  </div>
</div>

app/views/recordings/choosing.html.erb
<div class="col-lg-8 col-lg-offset-2 text-center">
  <h1><%= @recording.name %></h1>

  <hr class="v-space small" />

  <%= render_cell :recording, :setup, recording: @recording %>

  <hr class="v-space medium" />

  <h2><%= t 'choosing.title' %></h2>

  <hr class="v-space small" />

  <p><%= t 'choosing.text.html' %></p>

  <hr class="v-space large" />

</div>

<div class="col-sm-12 text-center">
  <% @recording.current_schedule.videos.in_groups_of(2).each do |video_group| %>
    <div class="row">
      <% video_group.each do |video| %>
        <div class="col-sm-6">
          <!-- the player -->
          <%= render_cell(:flowplayer, :show,
                          video: video,
                          ui_options: {length: true, time: true},
                          choose: {recording: @recording,
                                   video:     video},
                          info:  {duration: video.duration,
                                  size:     video.video_file_size,
                                  frames:   video.video_fps * video.duration}) if video %>
        </div>
      <% end %>
    </div>
    <hr class="v-space small">
  <% end %>
</div>

<div class="clearfix"></div>
<%= hr_with_text t('choosing.or')%>

<div class="col-lg-8 col-lg-offset-2 text-center">

  <h2><%= t 'choosing.try_again.title' %></h2>

  <p><%= t 'choosing.try_again.text.html' %></p>

  <%= render partial: "destroy_recording", locals: {recording: @recording} %>
</div>

app/views/recordings/in_progress.html.erb
<div class="col-lg-8 col-lg-offset-2 text-center">
  <h1><%= @recording.name %></h1>

  <hr class="v-space small" />

  <%= render_cell :recording, :setup, recording: @recording %>

  <hr class="v-space medium" />

  <h2><%= t 'in_progress.dont_worry' %></h2>

  <p>
    <% if @recording.current_schedule.recording_finished? %>
      <%= t 'in_progress.dont_worry_text.html', time: distance_of_time_in_words_to_now(@recording.current_schedule.make_utc_time(@recording.stop_at)), email: current_user.email %>
    <% else %>
      <%= t 'in_progress.generating_video_text.html', email: current_user.email %>
    <% end %>
  </p>
</div>

<div class="clearfix"></div>

<%= hr_with_text t('in_progress.or')%>

<div class="col-lg-8 col-lg-offset-2 text-center">
  <h2><%= t 'in_progress.try_again.title' %></h2>

  <p><%= t 'in_progress.try_again.text.html' %></p>

  <%= render partial: "destroy_recording", locals: {recording: @recording} %>
</div>

app/views/recordings/index.html.erb
<div class="col-lg-8 col-lg-offset-2 text-center">
  <h1>List of all your time-lapses</h1>
  <h3><small>You have <%= @recordings.count %> time-lapses</small></h3>

  <hr class="v-space medium">

  <%= link_to "Create new time-lapse", new_recording_path, class: "btn btn-lg btn-success" %>

  <hr class="v-space medium">

  <%= render @recordings %>
</div>

app/views/recordings/new.html.erb
<!-- TODO rozdělit na new a edit -->
<div class="col-md-8 col-md-offset-2 text-center">
  <h1>Set up your Time-lapse video</h1>
  <h2><small>just 2 simple steps</small></h2>

  <%= form_for @recording, html: {id: "recording-form", role: "form", class: "recording-form"} do |recording_form| %>

    <% @recording.build_current_schedule unless @recording.current_schedule
       @recording.current_schedule.camera_id = current_user.cameras.first.id if current_user.cameras.length == 1 %>

    <%= recording_form.fields_for :current_schedule do |schedule_form| %>

      <% schedule = schedule_form.object
         filter_exists = !!schedule.filter
         schedule.build_filter unless filter_exists %>

      <div class="recording-form_box recording-form_step-1">
        <h3>1. Select a camera</h3>
        <p>Choose a camera from which you want to create a time-lapse.</p>
        <div class="form-group col-xs-4 col-xs-offset-4">
          <%= schedule_form.collection_select :camera_id,
                                              current_user.cameras.sort {|a,b| a.shortname <=> b.shortname},
                                              :id, :shortname,
                                              {include_blank: t('form.choose_camera')},
                                              {class: "form-control js-camera-select"
                                               #,
                                               # :"data-cameras" => current_user.cameras.map {|c|
                                               #                      {id: c.id, shortname: c.shortname}
                                               #                    }.to_json
                                               } %>
        </div>

        <div class="clearfix"></div>
      </div>

      <div id="recording-form_step-2" class="<% unless schedule.camera_id? %>hidden<% end %> form-horizontal">
        <div class="recording-form_box">
          <h3>2. Set period</h3>
          <p>Set the time period from which time-lapse will be created.</p>

          <div class="col-lg-10 col-lg-offset-1 text-left">

            <!-- Start -->
            <div class="form-group form-horizontal <%= field_has_error_class schedule, :start_at %>">
              <label class="control-label col-xs-2 text-right">Start</label>

              <%= render partial: "date_picker", locals: {schedule_form: schedule_form, date_method: :start_at} %>

              <div class="recording-form__time-inputs form-inline">
                <%= time_input "#{schedule_form.object_name}[start_at_hash]", schedule.start_at, schedule.start_at_hash, ["12", "00", "AM"]%>
              </div>

              <div class="col-xs-offset-2 col-xs-10 recording-form__inputs-group">
                <%= errors_for schedule, :start_at %>
              </div>
            </div>

            <!-- Stop -->
            <div class="form-group form-horizontal <%= field_has_error_class schedule, :stop_at %>">
              <label class="control-label col-xs-2 text-right">Stop</label>

              <%= render partial: "date_picker", locals: {schedule_form: schedule_form, date_method: :stop_at} %>

              <div class="recording-form__time-inputs form-inline">
                <%= time_input "#{schedule_form.object_name}[stop_at_hash]", schedule.stop_at, schedule.stop_at_hash, ["11", "59", "PM"]%>
              </div>

              <div class="col-xs-offset-2 col-xs-10 recording-form__inputs-group">
                <%= errors_for schedule, :stop_at %>
              </div>
            </div>

            <!-- Timezone -->
            <div class="recording-form__timezone-text-row js-timezone-text-row hidden form-group">
              <div class="col-xs-offset-2">
                <span class="js-timezone-text-detected">
                  <span class="js-timezone-name"><%= schedule.active_support_timezone.to_s if schedule.active_support_timezone %></span>
                  <%= link_to_void "Wrong time zone?", class: "js-timezone-change" %>
                </span>
                <span class="js-timezone-text-detecting"><%= fa_icon "refresh spin", text: "Detecting timezone", right: true %></span>
              </div>
            </div>

            <div class="js-timezone-select-row form-group form-horizontal <%= field_has_error_class schedule, :timezone %>">
              <div class="col-xs-2 text-right">
                <%= schedule_form.label :timezone, class: "control-label" %>
              </div>

              <div class="recording-form__timezone-select">
                <%= schedule_form.select :timezone,
                                         ActiveSupport::TimeZone.all.map {|zone| [zone.to_s, zone.tzinfo.name]},
                                         {include_blank: "- Choose timezone -"},
                                         {class: "js-timezone-select form-control"} %>
              </div>

              <div class="col-xs-offset-2 col-xs-10 recording-form__inputs-group">
                <%= errors_for schedule, :timezone %>
              </div>
            </div>

            <!-- Filtr -->
            <div class="form-group">
              <div class="js-filter-toggle <%= "hidden" if filter_exists %>">
                You can set a <strong>time filter</strong> to record only between certain period of the day. <%= link_to_void "+ Add time filter" %>
              </div>

              <div class="js-filter <%= "hidden" unless filter_exists %>">
                <%= schedule_form.fields_for :filter do |filter_form| %>
                  <% filter = filter_form.object %>
                  <div class="<%= field_has_error_class filter, :from %> col-xs-2 text-right recording-form__filter-label">
                    <%= filter_form.label "#{filter_form.object_name}[from_hash]", "Record from", class: "control-label" %>
                  </div>

                  <div class="<%= field_has_error_class filter, :from %> form-inline recording-form__time-inputs">
                    <%= time_input "#{filter_form.object_name}[from_hash]", filter.from, filter.from_hash, [nil, nil, "AM"]%>
                    <%= errors_for filter, :from %>
                  </div>

                  <div class="<%= field_has_error_class filter, :to %> recording-form__filter-label-to text-right ">
                    <%= filter_form.label "#{filter_form.object_name}[to_hash]", "To", class: "control-label" %>
                  </div>

                  <div class="<%= field_has_error_class filter, :to %> form-inline recording-form__time-inputs">
                    <%= time_input "#{filter_form.object_name}[to_hash]", filter.to, filter.to_hash, [nil, nil, "PM"]%>
                    <%= errors_for filter, :to %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <div class="clearfix"></div>
        </div>

        <button type="submit" class="pull-right btn btn-lg btn-success">
          <%= fa_icon "arrow-circle-right", text: "Create time-lapse", right: true %>
        </button>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recordings/show.html.erb
<div class="col-lg-8 col-lg-offset-2 text-center">
  <h1><%= @recording.name %></h1>

  <hr class="v-space small" />

  <%= render_cell :recording, :setup, recording: @recording %>

  <hr class="v-space medium" />

  <%= render_cell :flowplayer, :show, video: @recording.final_video, ui_options: {length: true, time: true} %>

  <hr class="v-space medium" />

  <%= link_to "Download time-lapse", download_recording_path(@recording), class: "btn btn-large btn-primary" %>
</div>